
[gcp_service_account]
type = "service_account"
project_id = "singular-citron-459308-q0"
private_key_id = "d1b4b254a4174ec7951cfdab8b5ca509c306cf58"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC8qve1xkriolDu
ADQ8iuXsFo70CNs7HxLXgmf60+SD6X+F3p4fMrs6DF2Pbq4gPyipOX2J3C3ptAPY
cCbvEohSuFONgbIhumIZBVStmfDcRIEgPANS3qLhyu3B5xwgGBTApZCxu9xBsLat
nevZi3f4KllX6SoKoeGVkNhegGQzAjiBGKoXzr0fVS3DSrZSZBddtg6HYhBLEPkr
y5jiO+s6NoMzuUw25DGfPmod8EJ2ychD7DpePjxIFHFTvz198HwWWwqvXCqp8zqZ
+fnIyuLQz55abNs6lwupy0yC1e60KDWXqSMuXILXL9uDjN6LgP/z0RzmlI/4olp3
t85bmUH9AgMBAAECggEALt/BRHm8IDuYpNELKWGPB02BfdL3eORa/40oPVLIyxdH
tiBdo72sc5sf4aNrgpp+hTDB5m78PzyY2fzfR3WQxhCCvb0T3zpZ5gKDi9Ab3fXt
KO+QGdYznKqY0JyVScoB2e0ommfkrLN1Z4Q9VSLIDzGiWeuVpOecTtcaUrxOaLd+
ToJlUf/IVzDVJppdJYJpakVca+nXMS3pSVOj5wmdQejfBJB9AnNyaFaK/ERwgrTD
3zBJ8OqG+1Mro3FQpxyCmXl907D9wlUDWn9/ryfO2qfl/DpW5fwePNc+IUch2Mcn
fg3SdI9CoBoNM7YfRBonaCjnnUZb5GXer3Xb9Xf4pwKBgQDyPPyT0oCzXczls1H2
5Lgdxy1uriQh7iOyNURIxhe32MhSer6Bt6Rql+tsDvIml8/qeijy8eyJzzPBMP7h
sBGtxNOwtPWp0O3vzLko0D5v7Y2ZLbSHBnR1NI2Gqy9UGkl3o+T23q8cjXUk5ehk
ZD9DZnEzPqBW3xYbOUGqK58I+wKBgQDHYuARxJV7tFqwY690MNtK7s+FhGJNn+0e
2fZNNtZ47aIHOWx4fW8SmgnezCxwPDCYRbMxZI+E7TyeE6ibwZatFODMoYA93X9N
j5WateC+iWB25JCYr3IVpR3HN7/2UbBDKDANXRHGvT81h96mgLHmZnz+rpTXKTID
zuD/+z7fZwKBgQDLB2SnPQqTy22dpGNxbJgIlVU17Azqx17x0YVu/WEJvU+BGdGs
hU/v627tPcWlpR4lp8fEgBJCGwGEzd0DKgBXRZ4sAC/a6ftTPqJ+W7PJOjCxD0a8
2SMozShFlBryAapL9XlFlLTuWH2ztGLIKeGAS09bpQTcatRrctzflPoRmwKBgQC6
kA/tUC4249j/tybS52wpvy66VdbNn1j2Rygps6gW2vODIv4V9/hYRX361Ly3//nQ
YVd8XgXUcU8I8ogPxaJBLYnyryMZwAl//1wSuSAj6NM0LEYIOBHdovQsFkQuLN1q
2U2tE2qwtR9R7WIuFblgRoGqpJxsfwVnfsoVe3em/QKBgQCWD3NBLF7ne/D4087D
lAYz6dedCYq/5+gdWBQ/MFvJ2wt0kB9rR23gn6jsD2k9m5NljrkxeBPRsh/WOTQC
jGPKnNWHA03sSd9OyNza3eMLBh2QZawy+dGkbEjx6gkJ353D1M9Y5q0MJp4KAA74
pc3Iia3OzYz/YffMTlijEipY5A==
-----END PRIVATE KEY-----"""
client_email = "id-1-70@singular-citron-459308-q0.iam.gserviceaccount.com"
client_id = "113057271131956665821"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/id-1-70%40singular-citron-459308-q0.iam.gserviceaccount.com"